name: Pause
favicon: null
layout_spectrum: 0.63097
typography_spectrum: 0.20131
title: Pause Fest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#5cfaa1'
    - '#7a7a7a'
    - '#ffffff'
    - '#4c4c4c'
  brandStrength: 0
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
